### ISSUE TITLE
Add 'richtig' to direction keywords

### ISSUE THREAD

**Issue by johan-t** [FreiFahren/FreiFahren_BE-NLP#91]

**Comment by ngoldfine** [comment]
I'm interested in doing this. Just to confirm, the direction keywords you'd like adjusted are the `direction_keywords` list in process_message.py?

**Comment by johan-t** [comment]
> I'm interested in doing this. Just to confirm, the direction keywords you'd like adjusted are the `direction_keywords` list in process_message.py?

Yes exactly

**Comment by ngoldfine** [comment]
Thanks! I've submitted a pull request with the change
